config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  root 'home#index'

  resources :eventos

  resources :noticias

  resources :delegados

  get 'associados/admin' => 'associados#admin', as: :admin_associados
  resources :associados

  resources :galerias

end

app/models/associado.rb
class Associado < ActiveRecord::Base
  belongs_to :user
end

app/models/delegado.rb
class Delegado < ActiveRecord::Base
  validates :id_wca, presence: true, uniqueness: true

  validates_format_of :id_wca, with: /\A[0-9]{4}[A-Z]{4}[0-9]{2}\Z/
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  validates :nome, :data_inicio, :data_fim, :local, :endereco, presence: true

  before_validation :gerar_codigo
  private def gerar_codigo
    self.codigo = nome.parameterize
  end
end

app/models/noticia.rb
class Noticia < ActiveRecord::Base
  belongs_to :autor, class_name: 'User', foreign_key: :id_autor

  validates :slug, presence: true, uniqueness: true

  before_validation :compute_slug
  private def compute_slug
    self.slug = titulo.parameterize
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # has_many :inscricoes
  has_many :noticias, foreign_key: :id_autor
  has_one :associado

  attr_accessor :current_user

  def admin?
    tipo == 'a'
  end

  def diretoria?
    tipo == 'd'
  end

  def pode_postar_noticia?
    admin? || diretoria?
  end

  def pode_editar_associado?
    admin? || diretoria?
  end

  def pode_postar_evento?
    admin? || diretoria?
  end

  def pode_criar_delegado?
    admin?
  end
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # has_many :inscricoes
  has_one :associado

  attr_accessor :current_usuario

  def admin?
    tipo == 'a'
  end

  def diretoria?
    tipo == 'd'
  end

  def pode_postar_noticia?
    admin? || diretoria?
  end

  def pode_editar_associado?
    admin? || diretoria?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nome, :cidade, :estado, :id_wca, :id_forum])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nome, :cidade, :estado, :id_wca, :id_forum])
  end

  # Thanks, Jeremy!
  # https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/application_controller.rb#L39-L44
  private def redireciona_usuario(action, *args)
    return if current_user && current_user.send(action, *args)
    flash[:danger] = "Você não #{action.to_s.sub(/^can_/, '').chomp('?').humanize.downcase}"
    redirect_to root_url
  end
end

app/controllers/associados_controller.rb
class AssociadosController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action -> { redireciona_usuario(:pode_editar_associado?) }, except: [:index]

  def index
    @associados = Associado.where('data_vencimento > ?', Date.today)
  end

  def admin
    @usuarios = User.all
  end

  def create
    @associado = Associado.new(associado_params)
    if @associado.save
      flash[:success] = 'Salvo com sucesso'
      redirect_to admin_associados_path
    else
      flash[:danger] = 'Falha ao salvar!'
      render :edit
    end
  end

  def edit
    @associado = Associado.find_or_initialize_by(user_id: params[:id])
  end

  def update
    @associado = Associado.find(params[:id])
    if @associado.update_attributes(associado_params)
      flash[:success] = 'Salvo com sucesso'
      redirect_to admin_associados_path
    else
      flash[:danger] = 'Falha ao salvar!'
      render :edit
    end
  end

  def associado_params
    params.require(:associado).permit(:user_id, :data_cadastro, :data_vencimento)
  end
end

app/controllers/delegados_controller.rb
class DelegadosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action -> { redireciona_usuario(:pode_criar_delegado?) }, except: [:index, :show]

  def index
    @delegados = Delegado.all.order(:nome)
  end

  def new
    @delegado = Delegado.new
  end

  def create
    @delegado = Delegado.new(delegado_params)
    if @delegado.save
      flash[:success] = 'Delegado criado com sucesso!'
      redirect_to delegados_path
    else
      flash[:danger] = 'Falha ao criar delegado'
      render :new
    end
  end

  def edit
    @delegado = Delegado.find(params[:id])
  end

  def update
    @delegado = Delegado.find(params[:id])
    if @delegado.update_attributes(delegado_params)
      flash[:success] = 'Delegado salvo com sucesso!'
      redirect_to delegados_path
    else
      flash[:danger] = 'Falha ao salvar!'
      render :edit
    end
  end

  def delegado_params
    params.require(:delegado).permit(:nome, :email, :id_wca, :local)
  end
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action -> { redireciona_usuario(:pode_postar_evento?) }, except: [:index, :show]

  def index
    @eventos = Evento.order(:data_inicio)
  end

  def new
    @evento = Evento.new
  end

  def create
    @evento = Evento.new(evento_params)
    if @evento.save
      flash[:success] = 'Evento criado'
      redirect_to evento_path(@evento)
    else
      flash[:danger] = 'Falha ao criar evento'
      render :new
    end
  end

  def show
    @evento = Evento.find(params[:id])
  end

  def edit
    @evento = Evento.find(params[:id])
  end

  def update
    @evento = Evento.find(params[:id])
    if @evento.update_attributes(evento_params)
      flash[:success] = 'Evento salvo com sucesso!'
      redirect_to evento_path(@evento)
    else
      flash[:danger] = 'Falha ao salvar!'
      render :edit
    end
  end

  def destroy
  end

  def evento_params
    params.require(:evento).permit(:codigo, :nome, :data_inicio, :data_fim, :local, :endereco, :site_externo, :site, :intro, :modalidades, :cronograma, :inscricoes, :resultados)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/noticias_controller.rb
class NoticiasController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action -> { redireciona_usuario(:pode_postar_noticia?) }, except: [:index, :show]

  def index
    @noticias = Noticia.where(visivel: true).order(:created_at).reverse
  end

  def new
    @noticia = Noticia.new
  end

  def create
    @noticia = Noticia.new(noticia_params)
    @noticia.id_autor = current_user.id
    if @noticia.save
      flash[:success] = "Notícia criada"
      redirect_to edit_noticia_path(@noticia)
    else
      flash[:danger] = "Falha ao criar notícia"
      render :new
    end
  end

  def show
    @noticia = Noticia.find(params[:id])
  end

  def edit
    @noticia = Noticia.find(params[:id])
  end

  def update
    @noticia = Noticia.find(params[:id])
    if @noticia.update_attributes(noticia_params)
      flash[:success] = "Notícia salva com sucesso!"
      redirect_to noticia_path(@noticia)
    else
      flash[:danger] = 'Falha ao salvar!'
      render :edit
    end
  end

  def destroy
  end

  def noticia_params
    params.require(:noticia).permit(:titulo, :slug, :texto, :id_autor, :visivel)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: 'alert-success',
      danger: 'alert-danger',
      warning: 'alert-warning',
      info: 'alert-info',

      # For devise
      notice: 'alert-success',
      alert: 'alert-danger',

      recaptcha_error: 'alert-danger'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def reverse_icon(text, icon)
    text.html_safe + ' ' + content_tag(:i, '', class: "fa fa-#{icon}")
  end

  def glyphicon(icon)
    content_tag(:span, '', class: "glyphicon glyphicon-#{icon}")
  end
end

app/views/associados/admin.html.erb
<div class="container">
  <h2>Gerenciar associados</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Data de cadastro</th>
        <th>Data de vencimento</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @usuarios.each do |usuario| %>
        <tr class="">
          <td><%= usuario.id %></td>
          <td><%= usuario.nome %></td>
          <td><%= usuario.email %></td>
          <td><%=l usuario.associado.data_cadastro if usuario.associado.present? %></td>
          <td><%=l usuario.associado.data_vencimento if usuario.associado.present? %></td>
          <td><%= link_to icon('pencil','Editar'), edit_associado_path(usuario) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/associados/edit.html.erb
<div class="container">
  <h3>Editar Associado</h3>
  Nome: <%= @associado.user.nome %>
  <%= link_to "Editar cadastro", edit_user_registration_path(@associado.user), class: "btn btn-primary" %>
  <br /><br />
  <%= @associado.id %>
  <%= simple_form_for @associado do |f| %>
    <%= f.input :user_id %>
    <div class="daterange">
      <%= f.input :data_cadastro, as: :date_picker, label: "Data de registro" %>
      <%= f.input :data_vencimento, as: :date_picker, label: "Data de vencimento" %>
    </div>

    <button type="submit" class="btn btn-success">Enviar</button>
    <%= link_to root_url, class: "btn btn-warning" do %>
      <%= icon("remove") %> Cancelar
    <% end %>
  <% end %>
</div>

<script type="text/javascript">
$(function(){
  $('.date_picker.form-control').datetimepicker();
})
</script>

app/views/associados/index.html.erb
<div class="container">
  <h2>Associados</h2>
  <% if current_user && current_user.pode_editar_associado? %>
    <%= link_to icon('lock', 'Gerenciar'), admin_associados_path, class: "btn btn-info" %>
  <% end %>
  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Associado desde</th>
      </tr>
    </thead>
    <tbody>
      <% @associados.each do |associado| %>
        <tr>
          <td><%= associado.user.nome %></td>
          <td><%=l associado.data_cadastro, format: :default if associado.data_cadastro.present? %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/associados/new.html.erb
<div class="container">
  <h3>Cadastro de associado</h3>
  <p>Após o preenchimento do formulário, você receberá instruções para realizar o pagamento da taxa de inscrição anual no valor de R$ 50,00.</p>
  <%= simple_form_for @associado do |f| %>
    <%= f.input :nome, required: true, autofocus: true, label: "Nome completo" %>
    <%= f.input :email, required: true %>
    <%= f.input :cpf, required: true %>
    <%= f.input :identidade, required: true %>
    <%= f.input :endereco, required: true, label: "Endereço" %>
    <%= f.input :id_wca, required: false, label: "Id da WCA" %>
    <%= f.input :id_forum, required: false, label: "Id do forum" %>

    <button type="submit" class="btn btn-success">Enviar</button>
    <%= link_to root_url, class: "btn btn-warning" do %>
      <%= icon("remove") %> Cancelar
    <% end %>
  <% end %>
</div>

app/views/delegados/_form.html.erb
<%= simple_form_for @delegado do |f| %>
  <%= f.input :nome, required: true %>
  <%= f.input :id_wca, required: true %>
  <%= f.input :email, required: true %>
  <%= f.input :local, required: true %>
  <%= f.button :submit, "Salvar", class: "btn btn-success" %>

  <%= link_to icon('remove', 'Cancelar'), eventos_path, class: "btn btn-warning" %>
<% end %>

app/views/delegados/edit.html.erb
<div class="container">
  <h3>Editar delegado</h3>
  <div class="delegados-form">
    <%= render 'form'%>
  </div>
</div>

app/views/delegados/index.html.erb
<div class="container">
  <h2>Delegados</h2>
  <div class="delegados-index">
    <% @delegados.each do |delegado| %>
      <div class="delegado">
        <p><strong><%= delegado.nome %></strong>&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to "Resultados", "https://worldcubeassociation.org/results/p.php?i=#{delegado.id_wca}", target: '_blank' %>
          <% if current_user && current_user.pode_criar_delegado? %>
            &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to glyphicon('pencil') + " Editar", edit_delegado_path(delegado) %>
          <% end %>
        </p>
        <p class="email">
          E-mail: <%= delegado.email%>
        </p>
        <p class="local">
          Local: <%= delegado.local%>
        </p>
      </div>
    <% end %>
  </div>
  <% if current_user && current_user.pode_criar_delegado? %>
    <%= link_to glyphicon('plus') + " Novo delegado", new_delegado_path, class: "btn btn-success" %>
  <% end %>
</div>

app/views/delegados/new.html.erb
<div class="container">
  <h3>Cadastrar novo delegado</h3>
  <div class="delegados-form">
    <%= render 'form'%>
  </div>
</div>

app/views/eventos/_eventos.html.erb
<% eventos.each do |evento| %>
  <div class="evento">
    <h3 class="titulo"><%= evento.nome %></h3>
    <p class="data">
      Data: <%=l evento.data_inicio, format: :default %>
    </p>
    <p class="local">
      Local: <%= evento.local%>
    </p>
    <p class="mais">
      <%= link_to reverse_icon('Detalhes', 'arrow-right'), evento_path(evento), class: 'btn btn-primary' %>
    </p>
  </div>
<% end %>

app/views/eventos/_form.html.erb
<%= simple_form_for @evento do |f| %>
  <%= f.input :nome, required: true %>
  <%= f.input :data_inicio, required: true, label: "Data de início", as: :date_picker, html5: true %>
  <%= f.input :data_fim, required: true, label: "Data de término", as: :date_picker, html5: true %>
  <%= f.input :local, required: true %>
  <%= f.input :endereco, required: true, label: "Endereço" %>
  <%= f.input :site_externo, label: "Usar site externo?" %>
  <%= f.input :site %>
  <div class="esconder">
    <%= f.input :intro, label: "Introdução" %>
    <%= f.input :modalidades %>
    <%= f.input :cronograma %>
    <%= f.input :inscricoes, label: "Inscrições" %>
  </div>
  <%= f.input :resultados %>
  <%= f.button :submit, "Salvar", class: "btn btn-success" %>

  <%= link_to icon('remove', 'Cancelar'), eventos_path, class: "btn btn-warning" %>
<% end %>

app/views/eventos/index.html.erb
<div class="container">
  <h2>Eventos</h2>
  <div class="eventos-index">
    <%= render 'eventos', eventos: @eventos %>
  </div>
  <% if current_user && current_user.pode_postar_evento? %>
    <%= link_to glyphicon('plus') + " Novo evento", new_evento_path, class: "btn btn-success" %>
  <% end %>
</div>

app/views/eventos/new.html.erb
<div class="container">
  <h3>Cadastrar novo evento</h3>
  <div class="eventos-form">
    <%= render 'form'%>
  </div>
</div>

app/views/eventos/show.html.erb
<div class="container">
  <h3><%= @evento.nome %></h3>
  <p class="data">
    Data de início: <%=l @evento.data_inicio, format: :long %>
  </p>
  <p class="data">
    Data de término: <%=l @evento.data_inicio, format: :long %>
  </p>
  <p class="local">
    Local: <%= @evento.local%>
  </p>
  <p class="endereco">
    Endereço: <%= @evento.endereco%>
  </p>
  <% if @evento.site_externo %>
    <p class="site">
      Site: <%= @evento.site%>
    </p>
  <% else %>
    <p class="intro">
      Introdução: <%= @evento.intro%>
    </p>
    <p class="modalidades">
      Modalidades: <%= @evento.modalidades%>
    </p>
    <p class="cronograma">
      Cronograma: <%= @evento.cronograma%>
    </p>
    <p class="inscricoes">
      Inscriçoes: <%= @evento.inscricoes%>
    </p>
  <% end %>
  <p class="resultados">
    Resultados: <%= @evento.resultados%>
  </p>
  <% if current_user && current_user.pode_postar_evento? %>
    <%= link_to glyphicon('pencil') + " Editar", edit_evento_path(@evento), class: "btn btn-info" %>
  <% end %>
  <%= link_to glyphicon('arrow-left') + " Voltar", eventos_path, class: "btn btn-warning" %>
</div>

app/views/home/index.html.erb
<div class="container">
  <h2>Associação Brasileira de Cubo Mágico - ABCM</h2>
  <p>Bem-vindo!</p>
</div>

app/views/layouts/_flash.html.erb
<div id="flash-alerts" class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert <%= bootstrap_class_for message_type %> alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= message %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Associação Brasileira de Cubo Mágico - ABCM</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

<div class="container">
  <%= render 'layouts/flash' %>
  <%= yield %>
</div>

</body>
</html>

app/views/noticias/_noticias.html.erb
<% noticias.each do |noticia| %>
  <div class="noticia">
    <span class="titulo"><%= noticia.titulo %></span>
    <%#= noticia.texto[0...50] %>
    <span class="data">
      Postada em <%=l noticia.created_at, format: :post %>.
      <%# Esta subtração dá um resultado em segundos. 24h x 60 min x 60 seg = 86400 %>
      <% if (noticia.updated_at - noticia.created_at) > 86400 %>
        <br />Última atualização: <%=l noticia.updated_at, format: :post %>
      <% end %>
    </span>
    <span class="mais"><%= link_to reverse_icon('Continue lendo', 'arrow-right'), noticia_path(noticia), class: 'btn btn-primary' %></span>
  </div>
<% end %>

app/views/noticias/index.html.erb
<div class="container">
  <h2>Notícias</h2>
  <div class="noticias-index">
    <%= render 'noticias', noticias: @noticias %>
  </div>
  <% if current_user && current_user.pode_postar_noticia? %>
    <%= link_to glyphicon('plus') + " Nova notícia", new_noticia_path, class: "btn btn-success" %>
  <% end %>
</div>

app/views/noticias/show.html.erb
<div class="container">
  <h3><%= @noticia.titulo %></h3>
  <p>
    <%= @noticia.texto %>
  </p>
  <% if current_user && current_user.pode_postar_noticia? %>
    <%= link_to glyphicon('pencil') + " Editar", edit_noticia_path(@noticia), class: "btn btn-info" %>
  <% end %>
  <%= link_to glyphicon('arrow-left') + " Voltar", noticias_path, class: "btn btn-warning" %>
</div>